const START_INIT_APP = 'START_INIT_APP';
const LOADER_SHOW = 'LOADER_SHOW';
const LOADER_HIDE = 'LOADER_HIDE';
const COMPLETE_APP_INIT = 'COMPLETE_APP_INIT';

export { START_INIT_APP, LOADER_SHOW, LOADER_HIDE, COMPLETE_APP_INIT };